spring:
  application:
     name: PRODUCTSERVICE
     
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url : jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: "0614"
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  
server:
  port : 8081
